SRC = *.c

OBJ = ${SRC:.c=.o}

NAME = libftprintf.a
CC = gcc
CFLAGS = -Wall -Wextra -Werror -gcc

.c.o:
     ${CC} ${CFLAGS} -c $< -o ${<:.c=.o}

all:	$(NAME)

$(NAME):
          ${CC} ${FLAGS} -c ${src}
		  ar rc ${NAME} ${OBJ}
		  ranlib ${NAME}

clean:
      rm -f ${OBJ}

fclean: clean
      rm -f ${NAME}

re:
    fclean ${NAME}

.PHONY: all clean fclean re